# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b867a654786f523d645d8e59f8110b82467b1e2637f18e47638e8cf84c65e4de3883aa382eeb8dbbe627ab0ee5841ad3a7e37ceb813eed451f3b01d4d6fabe10

test:
  secret_key_base: c774b78fb552760a08567c12db492b543507b6293435223121eabed9127f370fe75428acfb9a97d25af9eb89c945da00fadd2dae5812521bb8474c5c9a850f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
